### LISTAR TODAS LAS CATEGORÍAS
GET http://localhost:3005/categoria

###

### OBTENER UNA CATEGORÍA POR ID
GET http://localhost:3005/categoria/1

###

### CREAR CATEGORÍA (Admin)
POST http://localhost:3005/categoria
Content-Type: application/json

{
   "categoria": "Videojuegos",
    "descripcion": "Juegos para distintas plataformas",
    "imagenCat": "https://storegamesperu.com/files/images/productos/1697557602-marvels-spider-man-2-ps5-pre-orden-0.jpg"
    }


###

### EDITAR CATEGORÍA (Admin)
PUT http://localhost:3005/categoria
Content-Type: application/json

{
  "id": 1,
  "categoria": "Consolas",
  "descripcion": "Consolas de videojuegos y accesorios oficiales",
  "imagenCat": "https://png.pngtree.com/png-vector/20250221/ourmid/pngtree-top-quality-playstation-5-console-isolated-png-image_15514648.png"
}


###

### ELIMINAR CATEGORÍA (Admin)
DELETE http://localhost:3005/categoria/2