### Obtener todos los usuarios
GET http://localhost:3005/usuario

### Obtener un usuario por id
GET http://localhost:3005/usuario/1


### Registrar usuario (con hash + token)
POST http://localhost:3005/usuario/registrar
Content-Type: application/json

{
  "nombre": "Aiden Gamer",
  "apellido": "RADO",
  "email": "aiden@example.com",
  "dni": "112222214",
  "password": "AidenNuevo123",
  "telefono": "969750401",
  "direccion": "Av. Gamer 123",
  "ciudad": "Lima",
  "admin": false
}


### Login usuario (devuelve token)
POST http://localhost:3005/usuario/login
Content-Type: application/json

{
  "email": "aiden@example.com",
  "password": "NuevaClaveRecuperada123"
}

###

PUT http://localhost:3005/usuario/1/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhaWRlbkBleGFtcGxlLmNvbSIsIm5vbWJyZSI6IkFpZGVuIEdhbWVyIiwiaWF0IjoxNzY0NTM0NTkxLCJleHAiOjE3NjUxMzkzOTF9.RDpPquLvaTUo0FTIUaoj7cng6ZcHHDrVGI3H_tHfXZI

{
  "passwordActual": "AidenActual123",
  "passwordNueva": "Aiden123"
}

### Solicitar recuperación (Simulado)
POST http://localhost:3005/usuario/recuperar-password
Content-Type: application/json

{
  "email": "aiden@example.com"
}

###

### Restablecer contraseña (Olvido)
POST http://localhost:3005/usuario/reset-password
Content-Type: application/json

{
  "email": "aiden@example.com",
  "newPassword": "NuevaClaveRecuperada123"
}
 